### ISSUE TITLE
ERROR: Error querying enabled displays on GPU 0 (Missing Extension).

### ISSUE THREAD

**Issue by tonymorella** [joernnilsson/nicehash-tools#1]
Getting this error when I run overclock.py, if I run nvidia-smi and nvidia_settings direct it work any ideas?

ERROR: Error querying enabled displays on GPU 0 (Missing Extension).
ERROR: Error querying connected displays on GPU 0 (Missing Extension).
ERROR: Error resolving target specification 'gpu:1' (No targets match target specification), specified in assignment '[gpu:1]/GPUPowerMizerMode=1'.

2018-08-12 04:04:03,857 [overclock.py        :  73] [DEBUG] nvidia-settings: '
'
Traceback (most recent call last):
  File "overclock.py", line 172, in <module>
    dev.set_clock_offset(args.clock)
  File "overclock.py", line 38, in set_clock_offset
    self.set_performance_mode()
  File "overclock.py", line 64, in set_performance_mode
    self.nvidia_settings(["-a", '[gpu:'+str(self.device_number)+']/GPUPowerMizerMode=1'])
  File "overclock.py", line 76, in nvidia_settings
    raise Exception("nvidia-settings exited with error %d" % (proc.returncode))
Exception: nvidia-settings exited with error 1

**Comment by tonymorella** [comment]
Ugg workaround was to export DISPLAY=:0.0
